### ISSUE TITLE
Improve the gRPC and OpenAPI ecosystem

### ISSUE THREAD

**Issue by iamrajiv** [wechaty/docusaurus#1012]
<div align="center">
<h1>Improve the gRPC and OpenAPI ecosystem</h1>
</div>

### Community Bonding (May 8 - May 17, 2021)

- [x] Zoom meeting schedule agreed.
- [x] Focus in the first two weeks before the start of the project will be on working through existing documentation and noting gaps areas.

### Week 1 (May 18 - May 24, 2021)

- [x] Getting familiar with Wechaty projects.
- [x] Going through all the existing contents and documentation based on gRPC and OpenAPI.
- [x] [#910](https://github.com/wechaty/docusaurus/pull/910): Adding Progressive Web Application support for the Docusaurus site.
- [x] [#1014](https://github.com/wechaty/docusaurus/pull/1014): Adding Progressive Web Application support for the Jekyll blog.

### Week 2 (May 25 - May 31, 2021)

In [Polyglot/OpenAPI](http://wechaty.js.org/docs/polyglot/openapi/) documentation in [Wechaty docs website](https://wechaty.js.org/docs/):

- [x] [#889](https://github.com/wechaty/docusaurus/pull/889): Adding Open Graph image metadata in the Docusaurus site of [wechaty.js.org](https://wechaty.js.org/).
- [x] [#917](https://github.com/wechaty/docusaurus/pull/917): Improving Wechaty OpenAPI docs.
- [x] [#929](https://github.com/wechaty/docusaurus/pull/929): Adding a blog about both gRPC and OpenAPI.

### Week 3 (June 1 - June 7, 2021)

In [Polyglot/OpenAPI](http://wechaty.js.org/docs/polyglot/openapi/) documentation in [Wechaty docs website](https://wechaty.js.org/docs/):

- [x] [#924](https://github.com/wechaty/docusaurus/pull/924): Updating the History section and fetching all contents of the `CHANGELOG.md` file from [wechaty/openapi](https://github.com/wechaty/openapi) repository using a script.
- [x] [#956](https://github.com/wechaty/docusaurus/pull/956): Adding learning resources section.

### Week 4 (June 8 - June 14, 2021)

- [x] [wechaty/grpc#135](https://github.com/wechaty/grpc/pull/135) and [wechaty/openapi#11](https://github.com/wechaty/openapi/pull/11): Generating and adding `CHANGELOG.md` file for both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository.
- [x] [wechaty/grpc#141](https://github.com/wechaty/grpc/pull/141) and [wechaty/openapi#18](https://github.com/wechaty/openapi/pull/18): Removing the `HISTORY` section part from README for both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository.

### Week 5 (June 15 - June 21, 2021)

- [x] [wechaty/grpc#139](https://github.com/wechaty/grpc/pull/139) and [wechaty/openapi#14](https://github.com/wechaty/openapi/pull/14): Adding issue and pull request templates for [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repositories.
- [x] [wechaty/grpc#140](https://github.com/wechaty/grpc/pull/140) and [wechaty/openapi#16](https://github.com/wechaty/openapi/pull/16): Adding `CONTRIBUTING.md` file for both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository.
- [x] [#1276](https://github.com/wechaty/docusaurus/pull/1276): Improving contributing guidelines of [wechaty.js.org](https://wechaty.js.org/).

### Week 6 (June 22 - June 28, 2021)

- [x] [wechaty/openapi#13](https://github.com/wechaty/openapi/pull/13): Adding Swagger UI to Express Route by default in [wechaty/openapi](https://github.com/wechaty/openapi) repository.

### Week 7 (June 29 - July 4, 2021)

- [x] [wechaty/grpc#141](https://github.com/wechaty/grpc/pull/141) and [wechaty/openapi#18](https://github.com/wechaty/openapi/pull/18): Adding and organizing learning resources section about third parties library and frameworks like gRPC, gRPC-Gateway, and Protocol Buffers, etc in both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository.
- [x] [wechaty/grpc#141](https://github.com/wechaty/grpc/pull/141) and [wechaty/openapi#18](https://github.com/wechaty/openapi/pull/18): Creating logo for [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) repository.

### Week 8 (July 5 - July 11, 2021)

- [x] [wechaty/grpc#141](https://github.com/wechaty/grpc/pull/141) and [wechaty/openapi#18](https://github.com/wechaty/openapi/pull/18): Refactoring and breaking the READMEs for both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository into sub-section like Usage, Installation, Contributing, and Resources, etc.
- [x] [wechaty/grpc#142](https://github.com/wechaty/grpc/pull/142) and [wechaty/openapi#19](https://github.com/wechaty/openapi/pull/19): Format files that are necessary using [Prettier](https://prettier.io) for both [wechaty/wechaty-grpc](https://github.com/wechaty/grpc) and [wechaty/openapi](https://github.com/wechaty/openapi) repository.
- [x] Checking and fixing indentations, grammatical errors, typographical errors, and broken links across all the files, including previous and new documentations.

### Week 9 (July 12 - July 18, 2021)

- [x] Finalizing the project deliverables and refactoring the code, if any, based on the feedback.
- [x] Making the project report.
- [x] [#1383](https://github.com/wechaty/docusaurus/pull/1383): Finalizing and submitting the project report.

---

## Extra Work

- [[GSoD 2021] Fixed typo in message.proto](https://github.com/wechaty/grpc/pull/133)
- [[GSoD 2021] Fixed favicon in Jekyll blog](https://github.com/wechaty/docusaurus/pull/880)
- [[GSoD 2021] Wrapped the string literals in a JSX container](https://github.com/wechaty/docusaurus/pull/1008)
- [[GSoD 2021] Removed the console expression](https://github.com/wechaty/docusaurus/pull/1010)
- [[GSoD 2021] Converted all Jekyll blog contributors images to webp](https://github.com/wechaty/docusaurus/pull/1072)

**Comment by iamrajiv** [comment]
Hi, @proudofsimin @Rohitesh-Kumar-Jain can you please review my PRs. I have completed all tasks and organized everything in this repository <https://github.com/iamrajiv/GSoD-2021>. Also, I have linked all PRs and relevant links to this issue so it will be easy to redirect. I have already tagged you in most of the PRs and for some PR even I am not sure to tag since you said you are not comfortable to review but according to #1045 volunteers, approval is mandatory for all PRs so please confirm this.

Apart from this, my other tasks left are:

- Link my project to old blogs because my project was selected at last and refactor my old proposal.
- Making a midterm report and convert it into a blog.
- Making a final report and convert it into a blog.

I have started writing my midterm report and will make a PR for the midterm blog soon but it would be great if my PRs get feedback or merged because this will help me to structure my blogs more concisely. After all, once blogs get merged it is hard to update them again and make PRs.

@huan @lijiarui

**Comment by iamrajiv** [comment]
@huan @lijiarui @profthecopyright @Rohitesh-Kumar-Jain PRs related to [wechaty/grpc](https://github.com/wechaty/grpc) repository are failing tests of `Go` and `PHP` because `Go` and `PHP` actions have bugs. Also, the PRs are related to `.md` files so we can ignore `Go` and `PHP` tests.

Reference:

- https://github.com/wechaty/grpc/issues/123
- https://github.com/wechaty/grpc/issues/124

**Comment by huan** [comment]
@iamrajiv thanks for all efforts that you have done for improving the grpc ecosystem.

Will review the related PRs this week.
